[build]
  command = "bash setup.sh && flutter pub get && flutter build web --release"
  publish = "build/web"

[build.environment]
  FLUTTER_CHANNEL = "stable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/flutter_service_worker.js"
  [headers.values]
    Cache-Control = "no-cache"
