[build.environment]
  FLUTTER_CHANNEL = "stable"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# لا تكاشي index.html و SW
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/flutter_service_worker.js"
  [headers.values]
    Cache-Control = "no-cache"

# كاش طويل للأصول
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/flutter.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/main.dart.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
